import type { Unit } from '../types/lesson'

/**
 * Original beginner Slovak curriculum for Slovo.
 * Diacritics: á ä č ď é í ĺ ľ ň ó ô ŕ š ť ú ý ž
 */
export const curriculum: Unit[] = [
  {
    id: 'unit-1',
    title: 'Greetings & Basics',
    description: 'Say hello, introduce yourself, and learn polite essentials.',
    color: '#22c55e',
    lessons: [
      {
        id: 'u1-l1',
        title: 'Hello!',
        description: 'Basic greetings',
        xp: 15,
        exercises: [
          {
            id: 'u1l1-1',
            type: 'multiple_choice',
            prompt: 'How do you say "Hello" in Slovak?',
            promptHint: 'Ahoj (AH-hoy)',
            options: ['Ahoj', 'Dovidenia', 'Prosím', 'Ďakujem'],
            correctIndex: 0,
          },
          {
            id: 'u1l1-2',
            type: 'word_match',
            prompt: 'Good morning',
            promptHint: 'Dobré ráno',
            options: ['Dobré ráno', 'Dobrý deň', 'Dobrý večer', 'Dobré popoludnie'],
            correctIndex: 0,
          },
          {
            id: 'u1l1-3',
            type: 'fill_blank',
            sentence: '___ deň!',
            translation: 'Good day!',
            options: ['Dobrý', 'Veľký', 'Milý', 'Nový'],
            correctIndex: 0,
            promptHint: 'Dobrý deň (DOH-bree dyen)',
          },
          {
            id: 'u1l1-4',
            type: 'translate_tiles',
            prompt: 'Translate: Good evening',
            promptHint: 'Dobrý večer',
            answer: ['Dobrý', 'večer'],
            distractors: ['ráno', 'Ahoj', 'noc'],
          },
          {
            id: 'u1l1-5',
            type: 'multiple_choice',
            prompt: 'What does "Dovidenia" mean?',
            options: ['Goodbye', 'Please', 'Thank you', 'Yes'],
            correctIndex: 0,
          },
          {
            id: 'u1l1-6',
            type: 'match_pairs',
            prompt: 'Match the greetings',
            pairs: [
              { left: 'Ahoj', right: 'Hi / Hello' },
              { left: 'Dovidenia', right: 'Goodbye' },
              { left: 'Dobré ráno', right: 'Good morning' },
              { left: 'Dobrý večer', right: 'Good evening' },
            ],
          },
          {
            id: 'u1l1-7',
            type: 'word_match',
            prompt: 'See you later',
            options: ['Čau', 'Áno', 'Nie', 'Prosím'],
            correctIndex: 0,
            promptHint: 'Čau (chow) — casual bye',
          },
          {
            id: 'u1l1-8',
            type: 'fill_blank',
            sentence: 'Dobré ___!',
            translation: 'Good morning!',
            options: ['ráno', 'jedlo', 'meno', 'mesto'],
            correctIndex: 0,
          },
          {
            id: 'u1l1-9',
            type: 'multiple_choice',
            prompt: 'Which is a formal daytime greeting?',
            options: ['Dobrý deň', 'Čau', 'Ahoj', 'Pá'],
            correctIndex: 0,
          },
          {
            id: 'u1l1-10',
            type: 'translate_tiles',
            prompt: 'Translate: Hello!',
            answer: ['Ahoj'],
            distractors: ['Nie', 'Áno', 'Prosím'],
          },
          {
            id: 'u1l1-11',
            type: 'say_this',
            target: 'Ahoj',
            meaning: 'Hello / Hi',
          },
          {
            id: 'u1l1-12',
            type: 'say_this',
            target: 'Dobré ráno',
            meaning: 'Good morning',
            acceptedAnswers: ['Dobre rano', 'Dobré rano'],
          },
],
      },
      {
        id: 'u1-l2',
        title: 'Please & Thanks',
        description: 'Polite words',
        xp: 15,
        exercises: [
          {
            id: 'u1l2-1',
            type: 'multiple_choice',
            prompt: 'How do you say "Thank you"?',
            promptHint: 'Ďakujem (DYAH-koo-yem)',
            options: ['Ďakujem', 'Prosím', 'Prepáčte', 'Áno'],
            correctIndex: 0,
          },
          {
            id: 'u1l2-2',
            type: 'word_match',
            prompt: 'Please / You\'re welcome',
            options: ['Prosím', 'Ďakujem', 'Nie', 'Dobre'],
            correctIndex: 0,
            promptHint: 'Prosím (PRO-seem)',
          },
          {
            id: 'u1l2-3',
            type: 'fill_blank',
            sentence: '___ , kde je toaleta?',
            translation: 'Please, where is the toilet?',
            options: ['Prosím', 'Ahoj', 'Áno', 'Čau'],
            correctIndex: 0,
          },
          {
            id: 'u1l2-4',
            type: 'match_pairs',
            pairs: [
              { left: 'Ďakujem', right: 'Thank you' },
              { left: 'Prosím', right: 'Please' },
              { left: 'Prepáčte', right: 'Excuse me / Sorry' },
              { left: 'Áno', right: 'Yes' },
            ],
          },
          {
            id: 'u1l2-5',
            type: 'multiple_choice',
            prompt: 'What does "Nie" mean?',
            options: ['No', 'Yes', 'Maybe', 'Hello'],
            correctIndex: 0,
          },
          {
            id: 'u1l2-6',
            type: 'translate_tiles',
            prompt: 'Translate: Thank you very much',
            promptHint: 'Ďakujem pekne',
            answer: ['Ďakujem', 'pekne'],
            distractors: ['Prosím', 'Ahoj', 'veľa'],
          },
          {
            id: 'u1l2-7',
            type: 'word_match',
            prompt: 'Excuse me (formal)',
            options: ['Prepáčte', 'Ahoj', 'Dobre', 'Tu'],
            correctIndex: 0,
          },
          {
            id: 'u1l2-8',
            type: 'fill_blank',
            sentence: '___ alebo nie?',
            translation: 'Yes or no?',
            options: ['Áno', 'Čaj', 'Mesto', 'Ráno'],
            correctIndex: 0,
          },
          {
            id: 'u1l2-9',
            type: 'multiple_choice',
            prompt: '"Ste milý/milá" is a way to say…',
            options: ["You're welcome / You're kind", 'Goodbye', 'Good night', 'How are you?'],
            correctIndex: 0,
          },
          {
            id: 'u1l2-10',
            type: 'translate_tiles',
            prompt: 'Translate: Yes, please',
            answer: ['Áno', 'prosím'],
            distractors: ['Nie', 'Ďakujem', 'Ahoj'],
          },
          {
            id: 'u1l2-11',
            type: 'say_this',
            target: 'Ďakujem',
            meaning: 'Thank you',
            acceptedAnswers: ['Dakujem'],
          },
          {
            id: 'u1l2-12',
            type: 'say_this',
            target: 'Prosím',
            meaning: "Please / You're welcome",
            acceptedAnswers: ['Prosim'],
          },
],
      },
      {
        id: 'u1-l3',
        title: 'How are you?',
        description: 'Asking & answering',
        xp: 20,
        exercises: [
          {
            id: 'u1l3-1',
            type: 'multiple_choice',
            prompt: 'How do you ask "How are you?" (informal)',
            promptHint: 'Ako sa máš?',
            options: ['Ako sa máš?', 'Ako sa voláš?', 'Kde bývaš?', 'Čo robíš?'],
            correctIndex: 0,
          },
          {
            id: 'u1l3-2',
            type: 'word_match',
            prompt: "I'm fine",
            options: ['Mám sa dobre', 'Som hladný', 'Neviem', 'Idem'],
            correctIndex: 0,
            promptHint: 'Mám sa dobre',
          },
          {
            id: 'u1l3-3',
            type: 'fill_blank',
            sentence: 'Ako sa ___?',
            translation: 'How are you?',
            options: ['máš', 'voláš', 'volá', 'má'],
            correctIndex: 0,
          },
          {
            id: 'u1l3-4',
            type: 'translate_tiles',
            prompt: 'Translate: How are you?',
            answer: ['Ako', 'sa', 'máš'],
            distractors: ['voláš', 'Dobrý', 'deň'],
          },
          {
            id: 'u1l3-5',
            type: 'match_pairs',
            pairs: [
              { left: 'Ako sa máš?', right: 'How are you?' },
              { left: 'Mám sa dobre', right: "I'm fine" },
              { left: 'A ty?', right: 'And you?' },
              { left: 'Výborne', right: 'Excellent / Great' },
            ],
          },
          {
            id: 'u1l3-6',
            type: 'multiple_choice',
            prompt: 'What does "A ty?" mean?',
            options: ['And you?', 'Who?', 'Where?', 'Why?'],
            correctIndex: 0,
          },
          {
            id: 'u1l3-7',
            type: 'word_match',
            prompt: 'Great! / Excellent!',
            options: ['Výborne', 'Zle', 'Pomaly', 'Neskoro'],
            correctIndex: 0,
          },
          {
            id: 'u1l3-8',
            type: 'fill_blank',
            sentence: 'Mám sa ___.',
            translation: "I'm fine.",
            options: ['dobre', 'ráno', 'večer', 'doma'],
            correctIndex: 0,
          },
          {
            id: 'u1l3-9',
            type: 'translate_tiles',
            prompt: "Translate: I'm fine, and you?",
            answer: ['Mám', 'sa', 'dobre', 'a', 'ty'],
            distractors: ['zle', 'Ahoj'],
          },
          {
            id: 'u1l3-10',
            type: 'multiple_choice',
            prompt: 'Formal "How are you?" is…',
            options: ['Ako sa máte?', 'Ako sa máš?', 'Čo je?', 'Kde si?'],
            correctIndex: 0,
          },
          {
            id: 'u1l3-11',
            type: 'say_this',
            target: 'Ako sa máš?',
            meaning: 'How are you? (informal)',
            acceptedAnswers: ['Ako sa mas', 'Ako sa máš'],
          },
],
      },
      {
        id: 'u1-l4',
        title: "What's your name?",
        description: 'Names & introductions',
        xp: 20,
        exercises: [
          {
            id: 'u1l4-1',
            type: 'multiple_choice',
            prompt: 'How do you ask "What is your name?" (informal)',
            promptHint: 'Ako sa voláš?',
            options: ['Ako sa voláš?', 'Ako sa máš?', 'Odkiaľ si?', 'Koľko máš rokov?'],
            correctIndex: 0,
          },
          {
            id: 'u1l4-2',
            type: 'translate_tiles',
            prompt: 'Translate: My name is Anna',
            promptHint: 'Volám sa Anna',
            answer: ['Volám', 'sa', 'Anna'],
            distractors: ['Som', 'Ahoj', 'ja'],
          },
          {
            id: 'u1l4-3',
            type: 'fill_blank',
            sentence: 'Volám ___ Peter.',
            translation: 'My name is Peter.',
            options: ['sa', 'som', 'je', 'má'],
            correctIndex: 0,
          },
          {
            id: 'u1l4-4',
            type: 'word_match',
            prompt: 'Nice to meet you',
            options: ['Teší ma', 'Ďakujem', 'Prosím', 'Dovidenia'],
            correctIndex: 0,
            promptHint: 'Teší ma (TEH-shee mah)',
          },
          {
            id: 'u1l4-5',
            type: 'match_pairs',
            pairs: [
              { left: 'Ako sa voláš?', right: 'What is your name?' },
              { left: 'Volám sa…', right: 'My name is…' },
              { left: 'Teší ma', right: 'Nice to meet you' },
              { left: 'Som zo Slovenska', right: "I'm from Slovakia" },
            ],
          },
          {
            id: 'u1l4-6',
            type: 'multiple_choice',
            prompt: 'What does "Som zo Slovenska" mean?',
            options: ["I'm from Slovakia", "I'm Slovak", 'I live here', 'I speak Slovak'],
            correctIndex: 0,
          },
          {
            id: 'u1l4-7',
            type: 'fill_blank',
            sentence: '___ ma!',
            translation: 'Nice to meet you!',
            options: ['Teší', 'Volá', 'Má', 'Ide'],
            correctIndex: 0,
          },
          {
            id: 'u1l4-8',
            type: 'translate_tiles',
            prompt: 'Translate: What is your name?',
            answer: ['Ako', 'sa', 'voláš'],
            distractors: ['máš', 'ďakujem'],
          },
          {
            id: 'u1l4-9',
            type: 'word_match',
            prompt: 'I am…',
            options: ['Som', 'Mám', 'Idem', 'Chcem'],
            correctIndex: 0,
          },
          {
            id: 'u1l4-10',
            type: 'multiple_choice',
            prompt: 'Respond to "Ako sa voláš?" with…',
            options: ['Volám sa…', 'Mám sa dobre', 'Áno, prosím', 'Dobrý deň'],
            correctIndex: 0,
          },
        ],
      },

      {
        id: 'u1-l5',
        title: 'Where are you from?',
        description: 'Origin & languages',
        xp: 20,
        exercises: [
          {
            id: 'u1l5-1',
            type: 'multiple_choice',
            prompt: 'How do you ask "Where are you from?" (informal)',
            promptHint: 'Odkiaľ si?',
            options: ['Odkiaľ si?', 'Ako sa voláš?', 'Ako sa máš?', 'Kde bývaš?'],
            correctIndex: 0,
          },
          {
            id: 'u1l5-2',
            type: 'translate_tiles',
            prompt: "Translate: I'm from Slovakia",
            promptHint: 'Som zo Slovenska',
            answer: ['Som', 'zo', 'Slovenska'],
            distractors: ['do', 'na', 'Ahoj'],
          },
          {
            id: 'u1l5-3',
            type: 'fill_blank',
            sentence: '___ po anglicky.',
            translation: 'I speak English.',
            options: ['Hovorím', 'Idem', 'Mám', 'Chcem'],
            correctIndex: 0,
            promptHint: 'Hovorím (HO-vo-reem)',
          },
          {
            id: 'u1l5-4',
            type: 'word_match',
            prompt: 'I live here',
            options: ['Bývam tu', 'Som tu', 'Idem tu', 'Mám tu'],
            correctIndex: 0,
            promptHint: 'Bývam tu',
          },
          {
            id: 'u1l5-5',
            type: 'match_pairs',
            pairs: [
              { left: 'Odkiaľ si?', right: 'Where are you from?' },
              { left: 'Som z…', right: "I'm from…" },
              { left: 'Hovorím po…', right: 'I speak…' },
              { left: 'Bývam tu', right: 'I live here' },
            ],
          },
          {
            id: 'u1l5-6',
            type: 'multiple_choice',
            prompt: 'What does "Odkiaľ ste?" mean?',
            options: ['Where are you from? (formal)', 'How are you?', 'What is your name?', 'Where do you work?'],
            correctIndex: 0,
          },
          {
            id: 'u1l5-7',
            type: 'fill_blank',
            sentence: 'Som ___ Prahy.',
            translation: "I'm from Prague.",
            options: ['z', 'do', 'na', 'o'],
            correctIndex: 0,
          },
          {
            id: 'u1l5-8',
            type: 'translate_tiles',
            prompt: 'Translate: I speak a little Slovak',
            answer: ['Hovorím', 'trochu', 'po', 'slovensky'],
            distractors: ['veľa', 'vôbec'],
          },
          {
            id: 'u1l5-9',
            type: 'word_match',
            prompt: 'a little / a bit',
            options: ['trochu', 'veľa', 'nič', 'všetko'],
            correctIndex: 0,
          },
          {
            id: 'u1l5-10',
            type: 'multiple_choice',
            prompt: 'How do you say "Welcome!"?',
            options: ['Vitajte!', 'Dovidenia!', 'Prepáčte!', 'Výborne!'],
            correctIndex: 0,
            promptHint: 'Vitajte (formal plural) / Vitaj (informal)',
          },
          {
            id: 'u1l5-11',
            type: 'say_this',
            target: 'Odkiaľ si?',
            meaning: 'Where are you from? (informal)',
            acceptedAnswers: ['Odkial si', 'Odkiaľ si'],
          },
          {
            id: 'u1l5-12',
            type: 'say_this',
            target: 'Hovorím po slovensky',
            meaning: 'I speak Slovak',
            acceptedAnswers: ['Hovorim po slovensky', 'Hovorím po slovensky'],
          },
        ],
      },
      {
        id: 'u1-l6',
        title: 'Useful phrases',
        description: 'Everyday polite lines',
        xp: 20,
        exercises: [
          {
            id: 'u1l6-1',
            type: 'multiple_choice',
            prompt: 'How do you say "Good night"?',
            promptHint: 'Dobrú noc',
            options: ['Dobrú noc', 'Dobré ráno', 'Dobrý deň', 'Dobrý večer'],
            correctIndex: 0,
          },
          {
            id: 'u1l6-2',
            type: 'word_match',
            prompt: 'Welcome (informal)',
            options: ['Vitaj', 'Ďakujem', 'Prosím', 'Čau'],
            correctIndex: 0,
          },
          {
            id: 'u1l6-3',
            type: 'fill_blank',
            sentence: 'Veľa ___.',
            translation: 'Good luck / Much happiness.',
            options: ['šťastia', 'vody', 'chleba', 'času'],
            correctIndex: 0,
            promptHint: 'Veľa šťastia',
          },
          {
            id: 'u1l6-4',
            type: 'match_pairs',
            pairs: [
              { left: 'Dobrú noc', right: 'Good night' },
              { left: 'Veľa šťastia', right: 'Good luck' },
              { left: 'Všetko najlepšie', right: 'All the best / Happy birthday' },
              { left: 'Na zdravie', right: 'Cheers / Bless you' },
            ],
          },
          {
            id: 'u1l6-5',
            type: 'translate_tiles',
            prompt: 'Translate: Good night',
            answer: ['Dobrú', 'noc'],
            distractors: ['ráno', 'deň', 'večer'],
          },
          {
            id: 'u1l6-6',
            type: 'multiple_choice',
            prompt: 'What does "Na zdravie" mean?',
            options: ['Cheers / Bless you', 'Good luck', 'Excuse me', 'See you'],
            correctIndex: 0,
          },
          {
            id: 'u1l6-7',
            type: 'word_match',
            prompt: 'See you tomorrow',
            options: ['Do zajtra', 'Dovidenia', 'Dobré ráno', 'Prepáč'],
            correctIndex: 0,
            promptHint: 'Do zajtra',
          },
          {
            id: 'u1l6-8',
            type: 'fill_blank',
            sentence: '___ najlepšie!',
            translation: 'All the best!',
            options: ['Všetko', 'Nič', 'Málo', 'Trochu'],
            correctIndex: 0,
          },
          {
            id: 'u1l6-9',
            type: 'multiple_choice',
            prompt: 'Informal "sorry" is…',
            options: ['Prepáč', 'Prepáčte', 'Ďakujem', 'Prosím'],
            correctIndex: 0,
          },
          {
            id: 'u1l6-10',
            type: 'translate_tiles',
            prompt: 'Translate: Good luck',
            answer: ['Veľa', 'šťastia'],
            distractors: ['vody', 'Ďakujem', 'ráno'],
          },
          {
            id: 'u1l6-11',
            type: 'say_this',
            target: 'Dobrú noc',
            meaning: 'Good night',
            acceptedAnswers: ['Dobru noc', 'Dobrú noc'],
          },
          {
            id: 'u1l6-12',
            type: 'say_this',
            target: 'Veľa šťastia',
            meaning: 'Good luck',
            acceptedAnswers: ['Vela stastia', 'Veľa šťastia', 'Vela šťastia'],
          },
        ],
      },
    ],
  },
  {
    id: 'unit-2',
    title: 'Numbers',
    description: 'Count from 0 to 20 and ask "how many?"',
    color: '#0ea5e9',
    lessons: [
      {
        id: 'u2-l1',
        title: '0–5',
        description: 'First numbers',
        xp: 15,
        exercises: [
          {
            id: 'u2l1-1',
            type: 'multiple_choice',
            prompt: 'What is "one" in Slovak?',
            promptHint: 'jeden (YEH-den)',
            options: ['jeden', 'dva', 'tri', 'nula'],
            correctIndex: 0,
          },
          {
            id: 'u2l1-2',
            type: 'word_match',
            prompt: 'two',
            options: ['dva', 'tri', 'štyri', 'päť'],
            correctIndex: 0,
          },
          {
            id: 'u2l1-3',
            type: 'fill_blank',
            sentence: 'Mám ___ jablká. (I have three apples.)',
            options: ['tri', 'jeden', 'nula', 'šesť'],
            correctIndex: 0,
          },
          {
            id: 'u2l1-4',
            type: 'match_pairs',
            pairs: [
              { left: 'nula', right: '0' },
              { left: 'jeden', right: '1' },
              { left: 'dva', right: '2' },
              { left: 'tri', right: '3' },
            ],
          },
          {
            id: 'u2l1-5',
            type: 'multiple_choice',
            prompt: 'What does "štyri" mean?',
            options: ['4', '3', '5', '6'],
            correctIndex: 0,
          },
          {
            id: 'u2l1-6',
            type: 'word_match',
            prompt: 'five',
            promptHint: 'päť (pyat\' )',
            options: ['päť', 'štyri', 'šesť', 'sedem'],
            correctIndex: 0,
          },
          {
            id: 'u2l1-7',
            type: 'translate_tiles',
            prompt: 'Translate: one, two, three',
            answer: ['jeden', 'dva', 'tri'],
            distractors: ['päť', 'nula'],
          },
          {
            id: 'u2l1-8',
            type: 'fill_blank',
            sentence: '___ plus dva je tri.',
            translation: 'One plus two is three.',
            options: ['Jeden', 'Päť', 'Štyri', 'Nula'],
            correctIndex: 0,
          },
          {
            id: 'u2l1-9',
            type: 'multiple_choice',
            prompt: '"Nula" means…',
            options: ['zero', 'nine', 'ten', 'none of these'],
            correctIndex: 0,
          },
          {
            id: 'u2l1-10',
            type: 'match_pairs',
            pairs: [
              { left: 'štyri', right: '4' },
              { left: 'päť', right: '5' },
              { left: 'tri', right: '3' },
              { left: 'dva', right: '2' },
            ],
          },
        ],
      },
      {
        id: 'u2-l2',
        title: '6–10',
        description: 'Next numbers',
        xp: 15,
        exercises: [
          {
            id: 'u2l2-1',
            type: 'multiple_choice',
            prompt: 'What is "six"?',
            options: ['šesť', 'sedem', 'osem', 'deväť'],
            correctIndex: 0,
            promptHint: 'šesť (shest\')',
          },
          {
            id: 'u2l2-2',
            type: 'word_match',
            prompt: 'seven',
            options: ['sedem', 'šesť', 'osem', 'desať'],
            correctIndex: 0,
          },
          {
            id: 'u2l2-3',
            type: 'fill_blank',
            sentence: 'Mám ___ euro. (I have eight euros.)',
            options: ['osem', 'deväť', 'päť', 'tri'],
            correctIndex: 0,
          },
          {
            id: 'u2l2-4',
            type: 'match_pairs',
            pairs: [
              { left: 'šesť', right: '6' },
              { left: 'sedem', right: '7' },
              { left: 'osem', right: '8' },
              { left: 'deväť', right: '9' },
            ],
          },
          {
            id: 'u2l2-5',
            type: 'multiple_choice',
            prompt: '"Desať" means…',
            options: ['10', '9', '11', '12'],
            correctIndex: 0,
          },
          {
            id: 'u2l2-6',
            type: 'translate_tiles',
            prompt: 'Translate: eight, nine, ten',
            answer: ['osem', 'deväť', 'desať'],
            distractors: ['šesť', 'jeden'],
          },
          {
            id: 'u2l2-7',
            type: 'word_match',
            prompt: 'nine',
            promptHint: 'deväť (DYEH-vyat\')',
            options: ['deväť', 'desať', 'sedem', 'päť'],
            correctIndex: 0,
          },
          {
            id: 'u2l2-8',
            type: 'fill_blank',
            sentence: 'Päť plus päť je ___.',
            options: ['desať', 'deväť', 'osem', 'šesť'],
            correctIndex: 0,
          },
          {
            id: 'u2l2-9',
            type: 'multiple_choice',
            prompt: 'Which number is "sedem"?',
            options: ['7', '6', '8', '17'],
            correctIndex: 0,
          },
          {
            id: 'u2l2-10',
            type: 'match_pairs',
            pairs: [
              { left: 'desať', right: '10' },
              { left: 'deväť', right: '9' },
              { left: 'osem', right: '8' },
              { left: 'sedem', right: '7' },
            ],
          },
        ],
      },
      {
        id: 'u2-l3',
        title: '11–20',
        description: 'Teens & twenty',
        xp: 20,
        exercises: [
          {
            id: 'u2l3-1',
            type: 'multiple_choice',
            prompt: 'What is "eleven"?',
            options: ['jedenásť', 'dvanásť', 'trinásť', 'dvadsať'],
            correctIndex: 0,
          },
          {
            id: 'u2l3-2',
            type: 'word_match',
            prompt: 'twelve',
            options: ['dvanásť', 'jedenásť', 'pätnásť', 'štrnásť'],
            correctIndex: 0,
          },
          {
            id: 'u2l3-3',
            type: 'match_pairs',
            pairs: [
              { left: 'trinásť', right: '13' },
              { left: 'štrnásť', right: '14' },
              { left: 'pätnásť', right: '15' },
              { left: 'šestnásť', right: '16' },
            ],
          },
          {
            id: 'u2l3-4',
            type: 'fill_blank',
            sentence: 'Mám ___ rokov. (I am twenty years old.)',
            options: ['dvadsať', 'desať', 'dvanásť', 'päť'],
            correctIndex: 0,
          },
          {
            id: 'u2l3-5',
            type: 'multiple_choice',
            prompt: '"Sedemnásť" means…',
            options: ['17', '16', '18', '27'],
            correctIndex: 0,
          },
          {
            id: 'u2l3-6',
            type: 'translate_tiles',
            prompt: 'Translate: fifteen',
            answer: ['pätnásť'],
            distractors: ['päť', 'desať', 'dvadsať'],
          },
          {
            id: 'u2l3-7',
            type: 'word_match',
            prompt: 'eighteen',
            options: ['osemnásť', 'devätnásť', 'sedemnásť', 'šestnásť'],
            correctIndex: 0,
          },
          {
            id: 'u2l3-8',
            type: 'multiple_choice',
            prompt: 'What is "twenty"?',
            options: ['dvadsať', 'dvanásť', 'dva', 'tridsať'],
            correctIndex: 0,
          },
          {
            id: 'u2l3-9',
            type: 'fill_blank',
            sentence: 'Jedenásť, dvanásť, ___.',
            options: ['trinásť', 'desať', 'dvadsať', 'päť'],
            correctIndex: 0,
          },
          {
            id: 'u2l3-10',
            type: 'match_pairs',
            pairs: [
              { left: 'sedemnásť', right: '17' },
              { left: 'osemnásť', right: '18' },
              { left: 'devätnásť', right: '19' },
              { left: 'dvadsať', right: '20' },
            ],
          },
        ],
      },
      {
        id: 'u2-l4',
        title: 'How many?',
        description: 'Asking for quantities',
        xp: 20,
        exercises: [
          {
            id: 'u2l4-1',
            type: 'multiple_choice',
            prompt: 'How do you say "How many?"',
            promptHint: 'Koľko?',
            options: ['Koľko?', 'Kde?', 'Kto?', 'Čo?'],
            correctIndex: 0,
          },
          {
            id: 'u2l4-2',
            type: 'translate_tiles',
            prompt: 'Translate: How many apples?',
            answer: ['Koľko', 'jabĺk'],
            distractors: ['Kde', 'tri', 'chlieb'],
          },
          {
            id: 'u2l4-3',
            type: 'fill_blank',
            sentence: '___ to stojí?',
            translation: 'How much does it cost?',
            options: ['Koľko', 'Kde', 'Kedy', 'Prečo'],
            correctIndex: 0,
          },
          {
            id: 'u2l4-4',
            type: 'word_match',
            prompt: 'a little / few',
            options: ['málo', 'veľa', 'všetko', 'nič'],
            correctIndex: 0,
          },
          {
            id: 'u2l4-5',
            type: 'match_pairs',
            pairs: [
              { left: 'Koľko?', right: 'How many / How much?' },
              { left: 'veľa', right: 'a lot / many' },
              { left: 'málo', right: 'a little / few' },
              { left: 'všetko', right: 'everything' },
            ],
          },
          {
            id: 'u2l4-6',
            type: 'multiple_choice',
            prompt: '"Veľa" means…',
            options: ['a lot / many', 'none', 'one', 'half'],
            correctIndex: 0,
          },
          {
            id: 'u2l4-7',
            type: 'fill_blank',
            sentence: 'Chcem ___ kávy.',
            translation: 'I want two coffees. (lit. two of coffee)',
            options: ['dve', 'jeden', 'veľa', 'málo'],
            correctIndex: 0,
          },
          {
            id: 'u2l4-8',
            type: 'translate_tiles',
            prompt: 'Translate: How much does it cost?',
            answer: ['Koľko', 'to', 'stojí'],
            distractors: ['Kde', 'je'],
          },
          {
            id: 'u2l4-9',
            type: 'word_match',
            prompt: 'nothing',
            options: ['nič', 'všetko', 'niečo', 'veľa'],
            correctIndex: 0,
          },
          {
            id: 'u2l4-10',
            type: 'multiple_choice',
            prompt: 'Which asks for a price?',
            options: ['Koľko to stojí?', 'Ako sa voláš?', 'Kde je to?', 'Čo robíš?'],
            correctIndex: 0,
          },
        ],
      },

      {
        id: 'u2-l5',
        title: 'Tens & 100',
        description: '20–100',
        xp: 20,
        exercises: [
          {
            id: 'u2l5-1',
            type: 'multiple_choice',
            prompt: 'How do you say "30"?',
            promptHint: 'tridsať',
            options: ['tridsať', 'dvadsať', 'štyridsať', 'päťdesiat'],
            correctIndex: 0,
          },
          {
            id: 'u2l5-2',
            type: 'word_match',
            prompt: '40',
            options: ['štyridsať', 'tridsať', 'päťdesiat', 'šesťdesiat'],
            correctIndex: 0,
          },
          {
            id: 'u2l5-3',
            type: 'match_pairs',
            pairs: [
              { left: 'dvadsať', right: '20' },
              { left: 'tridsať', right: '30' },
              { left: 'päťdesiat', right: '50' },
              { left: 'sto', right: '100' },
            ],
          },
          {
            id: 'u2l5-4',
            type: 'fill_blank',
            sentence: 'Mám ___ eur.',
            translation: 'I have fifty euros.',
            options: ['päťdesiat', 'päť', 'pätnásť', 'sto'],
            correctIndex: 0,
          },
          {
            id: 'u2l5-5',
            type: 'multiple_choice',
            prompt: '"Šesťdesiat" means…',
            options: ['60', '16', '6', '70'],
            correctIndex: 0,
          },
          {
            id: 'u2l5-6',
            type: 'word_match',
            prompt: '70',
            options: ['sedemdesiat', 'šesťdesiat', 'osemdesiat', 'deväťdesiat'],
            correctIndex: 0,
          },
          {
            id: 'u2l5-7',
            type: 'translate_tiles',
            prompt: 'Translate: one hundred',
            answer: ['sto'],
            distractors: ['desať', 'tisíc', 'nula'],
          },
          {
            id: 'u2l5-8',
            type: 'fill_blank',
            sentence: 'To stojí ___ eur.',
            translation: 'It costs eighty euros.',
            options: ['osemdesiat', 'osem', 'osemnásť', 'sto'],
            correctIndex: 0,
          },
          {
            id: 'u2l5-9',
            type: 'multiple_choice',
            prompt: 'How do you say "90"?',
            options: ['deväťdesiat', 'deväť', 'devätnásť', 'sedemdesiat'],
            correctIndex: 0,
          },
          {
            id: 'u2l5-10',
            type: 'match_pairs',
            pairs: [
              { left: 'štyridsať', right: '40' },
              { left: 'šesťdesiat', right: '60' },
              { left: 'osemdesiat', right: '80' },
              { left: 'deväťdesiat', right: '90' },
            ],
          },
          {
            id: 'u2l5-11',
            type: 'say_this',
            target: 'tridsať',
            meaning: 'thirty',
            acceptedAnswers: ['tridsat', 'tridsať'],
          },
          {
            id: 'u2l5-12',
            type: 'say_this',
            target: 'sto',
            meaning: 'one hundred',
          },
        ],
      },
      {
        id: 'u2-l6',
        title: 'Age & quantity',
        description: 'Years old and how many',
        xp: 20,
        exercises: [
          {
            id: 'u2l6-1',
            type: 'multiple_choice',
            prompt: 'How do you ask "How old are you?" (informal)',
            promptHint: 'Koľko máš rokov?',
            options: ['Koľko máš rokov?', 'Koľko to stojí?', 'Ako sa voláš?', 'Kde bývaš?'],
            correctIndex: 0,
          },
          {
            id: 'u2l6-2',
            type: 'translate_tiles',
            prompt: "Translate: I'm twenty years old",
            answer: ['Mám', 'dvadsať', 'rokov'],
            distractors: ['som', 'desať', 'eur'],
          },
          {
            id: 'u2l6-3',
            type: 'fill_blank',
            sentence: 'Mám ___ rokov.',
            translation: "I'm twenty-five years old.",
            options: ['dvadsaťpäť', 'päť', 'pätnásť', 'sto'],
            correctIndex: 0,
          },
          {
            id: 'u2l6-4',
            type: 'word_match',
            prompt: 'year / years (genitive plural form often "rokov")',
            options: ['rok', 'deň', 'mesiac', 'hodina'],
            correctIndex: 0,
          },
          {
            id: 'u2l6-5',
            type: 'match_pairs',
            pairs: [
              { left: 'Koľko máš rokov?', right: 'How old are you?' },
              { left: 'Mám … rokov', right: "I'm … years old" },
              { left: 'iba', right: 'only' },
              { left: 'asi', right: 'about / approximately' },
            ],
          },
          {
            id: 'u2l6-6',
            type: 'multiple_choice',
            prompt: '"Iba dva" means…',
            options: ['only two', 'about two', 'also two', 'not two'],
            correctIndex: 0,
          },
          {
            id: 'u2l6-7',
            type: 'fill_blank',
            sentence: 'Chcem ___ jablká.',
            translation: 'I want three apples.',
            options: ['tri', 'tridsať', 'tretí', 'trochu'],
            correctIndex: 0,
          },
          {
            id: 'u2l6-8',
            type: 'word_match',
            prompt: 'half',
            options: ['pol', 'celý', 'veľa', 'málo'],
            correctIndex: 0,
            promptHint: 'pol (as in pol hodiny — half an hour)',
          },
          {
            id: 'u2l6-9',
            type: 'translate_tiles',
            prompt: 'Translate: How old are you?',
            answer: ['Koľko', 'máš', 'rokov'],
            distractors: ['stojí', 'si'],
          },
          {
            id: 'u2l6-10',
            type: 'multiple_choice',
            prompt: 'What does "asi desať" mean?',
            options: ['about ten', 'only ten', 'exactly ten', 'not ten'],
            correctIndex: 0,
          },
          {
            id: 'u2l6-11',
            type: 'say_this',
            target: 'Koľko máš rokov?',
            meaning: 'How old are you?',
            acceptedAnswers: ['Kolko mas rokov', 'Koľko máš rokov'],
          },
          {
            id: 'u2l6-12',
            type: 'say_this',
            target: 'Mám dvadsať rokov',
            meaning: "I'm twenty years old",
            acceptedAnswers: ['Mam dvadsat rokov', 'Mám dvadsať rokov'],
          },
        ],
      },
    ],
  },
  {
    id: 'unit-3',
    title: 'Food & Drink',
    description: 'Order food, drinks, and say what you like.',
    color: '#f59e0b',
    lessons: [
      {
        id: 'u3-l1',
        title: 'Drinks',
        description: 'Water, coffee, tea…',
        xp: 15,
        exercises: [
          {
            id: 'u3l1-1',
            type: 'multiple_choice',
            prompt: 'How do you say "water"?',
            promptHint: 'voda (VOH-dah)',
            options: ['voda', 'mlieko', 'čaj', 'pivo'],
            correctIndex: 0,
          },
          {
            id: 'u3l1-2',
            type: 'word_match',
            prompt: 'coffee',
            options: ['káva', 'čaj', 'voda', 'víno'],
            correctIndex: 0,
          },
          {
            id: 'u3l1-3',
            type: 'fill_blank',
            sentence: 'Chcem ___, prosím.',
            translation: 'I want tea, please.',
            options: ['čaj', 'chlieb', 'mäso', 'soľ'],
            correctIndex: 0,
          },
          {
            id: 'u3l1-4',
            type: 'match_pairs',
            pairs: [
              { left: 'voda', right: 'water' },
              { left: 'káva', right: 'coffee' },
              { left: 'čaj', right: 'tea' },
              { left: 'mlieko', right: 'milk' },
            ],
          },
          {
            id: 'u3l1-5',
            type: 'translate_tiles',
            prompt: 'Translate: One coffee, please',
            answer: ['Jednu', 'kávu', 'prosím'],
            distractors: ['vodu', 'Ďakujem'],
          },
          {
            id: 'u3l1-6',
            type: 'multiple_choice',
            prompt: '"Pivo" means…',
            options: ['beer', 'wine', 'juice', 'soup'],
            correctIndex: 0,
          },
          {
            id: 'u3l1-7',
            type: 'word_match',
            prompt: 'wine',
            options: ['víno', 'pivo', 'voda', 'džús'],
            correctIndex: 0,
          },
          {
            id: 'u3l1-8',
            type: 'fill_blank',
            sentence: 'Bez ___ , prosím. (Without sugar, please.)',
            options: ['cukru', 'vody', 'čaju', 'mäsa'],
            correctIndex: 0,
          },
          {
            id: 'u3l1-9',
            type: 'multiple_choice',
            prompt: 'What does "džús" mean?',
            options: ['juice', 'soda', 'soup', 'ice'],
            correctIndex: 0,
          },
          {
            id: 'u3l1-10',
            type: 'translate_tiles',
            prompt: 'Translate: I want water',
            answer: ['Chcem', 'vodu'],
            distractors: ['kávu', 'som', 'nie'],
          },
          {
            id: 'u3l1-11',
            type: 'say_this',
            target: 'voda',
            meaning: 'water',
          },
          {
            id: 'u3l1-12',
            type: 'say_this',
            target: 'káva',
            meaning: 'coffee',
            acceptedAnswers: ['kava'],
          },
],
      },
      {
        id: 'u3-l2',
        title: 'Meals',
        description: 'Bread, soup, meat…',
        xp: 15,
        exercises: [
          {
            id: 'u3l2-1',
            type: 'multiple_choice',
            prompt: 'How do you say "bread"?',
            options: ['chlieb', 'syr', 'ryža', 'polievka'],
            correctIndex: 0,
            promptHint: 'chlieb (khlyeb)',
          },
          {
            id: 'u3l2-2',
            type: 'word_match',
            prompt: 'soup',
            options: ['polievka', 'mäso', 'ryba', 'šalát'],
            correctIndex: 0,
          },
          {
            id: 'u3l2-3',
            type: 'match_pairs',
            pairs: [
              { left: 'mäso', right: 'meat' },
              { left: 'ryba', right: 'fish' },
              { left: 'syr', right: 'cheese' },
              { left: 'vajce', right: 'egg' },
            ],
          },
          {
            id: 'u3l2-4',
            type: 'fill_blank',
            sentence: 'Jedávam ___ . (I eat salad.)',
            options: ['šalát', 'pivo', 'víno', 'čaj'],
            correctIndex: 0,
          },
          {
            id: 'u3l2-5',
            type: 'translate_tiles',
            prompt: 'Translate: bread and cheese',
            answer: ['chlieb', 'a', 'syr'],
            distractors: ['mäso', 'voda'],
          },
          {
            id: 'u3l2-6',
            type: 'multiple_choice',
            prompt: '"Ryža" means…',
            options: ['rice', 'fish', 'bread', 'potato'],
            correctIndex: 0,
          },
          {
            id: 'u3l2-7',
            type: 'word_match',
            prompt: 'potato / potatoes',
            options: ['zemiaky', 'jablko', 'mäso', 'cukor'],
            correctIndex: 0,
          },
          {
            id: 'u3l2-8',
            type: 'fill_blank',
            sentence: 'Chcem ___ , prosím. (I want soup, please.)',
            options: ['polievku', 'vodu', 'čaj', 'pivo'],
            correctIndex: 0,
          },
          {
            id: 'u3l2-9',
            type: 'multiple_choice',
            prompt: 'What is "jablko"?',
            options: ['apple', 'orange', 'banana', 'grape'],
            correctIndex: 0,
          },
          {
            id: 'u3l2-10',
            type: 'match_pairs',
            pairs: [
              { left: 'chlieb', right: 'bread' },
              { left: 'polievka', right: 'soup' },
              { left: 'šalát', right: 'salad' },
              { left: 'jablko', right: 'apple' },
            ],
          },
          {
            id: 'u3l2-11',
            type: 'say_this',
            target: 'chlieb',
            meaning: 'bread',
          },
          {
            id: 'u3l2-12',
            type: 'say_this',
            target: 'polievka',
            meaning: 'soup',
          },
],
      },
      {
        id: 'u3-l3',
        title: 'I like…',
        description: 'Likes & ordering',
        xp: 20,
        exercises: [
          {
            id: 'u3l3-1',
            type: 'multiple_choice',
            prompt: 'How do you say "I like…"?',
            promptHint: 'Mám rád / Mám rada',
            options: ['Mám rád', 'Nemám', 'Chcem', 'Som'],
            correctIndex: 0,
          },
          {
            id: 'u3l3-2',
            type: 'translate_tiles',
            prompt: 'Translate: I like coffee',
            answer: ['Mám', 'rád', 'kávu'],
            distractors: ['nemám', 'čaj', 'voda'],
          },
          {
            id: 'u3l3-3',
            type: 'fill_blank',
            sentence: '___ rád čokoládu.',
            translation: 'I like chocolate.',
            options: ['Mám', 'Som', 'Idem', 'Vidím'],
            correctIndex: 0,
          },
          {
            id: 'u3l3-4',
            type: 'word_match',
            prompt: "I don't like…",
            options: ['Nemám rád', 'Mám rád', 'Chcem', 'Prosím'],
            correctIndex: 0,
          },
          {
            id: 'u3l3-5',
            type: 'match_pairs',
            pairs: [
              { left: 'Mám rád', right: 'I like (m.)' },
              { left: 'Mám rada', right: 'I like (f.)' },
              { left: 'Chcem', right: 'I want' },
              { left: 'Jedálny lístok', right: 'menu' },
            ],
          },
          {
            id: 'u3l3-6',
            type: 'multiple_choice',
            prompt: '"Účet, prosím" means…',
            options: ['The bill, please', 'More, please', 'Water, please', 'Help, please'],
            correctIndex: 0,
          },
          {
            id: 'u3l3-7',
            type: 'fill_blank',
            sentence: '___, prosím. (The bill, please.)',
            options: ['Účet', 'Jedlo', 'Stôl', 'Nôž'],
            correctIndex: 0,
          },
          {
            id: 'u3l3-8',
            type: 'translate_tiles',
            prompt: 'Translate: I want the menu',
            answer: ['Chcem', 'jedálny', 'lístok'],
            distractors: ['účet', 'voda'],
          },
          {
            id: 'u3l3-9',
            type: 'word_match',
            prompt: 'delicious / tasty',
            options: ['chutné', 'horúce', 'studené', 'veľké'],
            correctIndex: 0,
          },
          {
            id: 'u3l3-10',
            type: 'multiple_choice',
            prompt: 'How do you say "I\'m hungry"?',
            options: ['Som hladný / hladná', 'Som smädný', 'Som unavený', 'Som šťastný'],
            correctIndex: 0,
          },
        ],
      },

      {
        id: 'u3-l4',
        title: 'Fruits & snacks',
        description: 'Apples, cheese, sweets…',
        xp: 20,
        exercises: [
          {
            id: 'u3l4-1',
            type: 'multiple_choice',
            prompt: 'How do you say "apple"?',
            promptHint: 'jablko',
            options: ['jablko', 'banán', 'hruška', 'pomaranč'],
            correctIndex: 0,
          },
          {
            id: 'u3l4-2',
            type: 'word_match',
            prompt: 'banana',
            options: ['banán', 'jablko', 'hrozno', 'jahoda'],
            correctIndex: 0,
          },
          {
            id: 'u3l4-3',
            type: 'match_pairs',
            pairs: [
              { left: 'jablko', right: 'apple' },
              { left: 'pomaranč', right: 'orange (fruit)' },
              { left: 'jahoda', right: 'strawberry' },
              { left: 'hrozno', right: 'grapes' },
            ],
          },
          {
            id: 'u3l4-4',
            type: 'fill_blank',
            sentence: 'Chcem ___, prosím.',
            translation: 'I want an orange, please.',
            options: ['pomaranč', 'polievku', 'účet', 'stôl'],
            correctIndex: 0,
          },
          {
            id: 'u3l4-5',
            type: 'translate_tiles',
            prompt: 'Translate: sweet / candy',
            answer: ['sladkosť'],
            distractors: ['soľ', 'chlieb', 'mäso'],
          },
          {
            id: 'u3l4-6',
            type: 'multiple_choice',
            prompt: '"Čokoláda" means…',
            options: ['chocolate', 'cheese', 'chicken', 'cherry'],
            correctIndex: 0,
          },
          {
            id: 'u3l4-7',
            type: 'word_match',
            prompt: 'ice cream',
            options: ['zmrzlina', 'mlieko', 'maslo', 'med'],
            correctIndex: 0,
            promptHint: 'zmrzlina',
          },
          {
            id: 'u3l4-8',
            type: 'fill_blank',
            sentence: 'Toto ___ je sladké.',
            translation: 'This fruit is sweet.',
            options: ['ovocie', 'mäso', 'pivo', 'chlieb'],
            correctIndex: 0,
          },
          {
            id: 'u3l4-9',
            type: 'multiple_choice',
            prompt: 'How do you say "pear"?',
            options: ['hruška', 'jablko', 'slivka', 'čerešňa'],
            correctIndex: 0,
          },
          {
            id: 'u3l4-10',
            type: 'match_pairs',
            pairs: [
              { left: 'banán', right: 'banana' },
              { left: 'zmrzlina', right: 'ice cream' },
              { left: 'čokoláda', right: 'chocolate' },
              { left: 'hruška', right: 'pear' },
            ],
          },
          {
            id: 'u3l4-11',
            type: 'say_this',
            target: 'jablko',
            meaning: 'apple',
          },
          {
            id: 'u3l4-12',
            type: 'say_this',
            target: 'Chcem zmrzlinu',
            meaning: 'I want ice cream',
            acceptedAnswers: ['Chcem zmrzlinu', 'Chcem zmrzlina'],
          },
        ],
      },
      {
        id: 'u3-l5',
        title: 'At the table',
        description: 'Ordering & table talk',
        xp: 20,
        exercises: [
          {
            id: 'u3l5-1',
            type: 'multiple_choice',
            prompt: 'How do you say "I\'m thirsty"?',
            options: ['Som smädný / smädná', 'Som hladný', 'Som unavený', 'Som spokojný'],
            correctIndex: 0,
            promptHint: 'Som smädný (m.) / smädná (f.)',
          },
          {
            id: 'u3l5-2',
            type: 'word_match',
            prompt: 'fork',
            options: ['vidlička', 'nôž', 'lyžica', 'tanier'],
            correctIndex: 0,
          },
          {
            id: 'u3l5-3',
            type: 'match_pairs',
            pairs: [
              { left: 'nôž', right: 'knife' },
              { left: 'lyžica', right: 'spoon' },
              { left: 'tanier', right: 'plate' },
              { left: 'pohár', right: 'glass / cup' },
            ],
          },
          {
            id: 'u3l5-4',
            type: 'fill_blank',
            sentence: 'Ešte ___, prosím.',
            translation: 'One more, please. / Still… please.',
            options: ['jedno', 'nič', 'účet', 'von'],
            correctIndex: 0,
            promptHint: 'Ešte jedno, prosím',
          },
          {
            id: 'u3l5-5',
            type: 'translate_tiles',
            prompt: 'Translate: Enjoy your meal',
            answer: ['Dobrú', 'chuť'],
            distractors: ['noc', 'ráno', 'voda'],
          },
          {
            id: 'u3l5-6',
            type: 'multiple_choice',
            prompt: '"Bez lepku" means…',
            options: ['gluten-free', 'sugar-free', 'dairy-free', 'spicy'],
            correctIndex: 0,
          },
          {
            id: 'u3l5-7',
            type: 'word_match',
            prompt: 'salt',
            options: ['soľ', 'cukor', 'korenie', 'olej'],
            correctIndex: 0,
          },
          {
            id: 'u3l5-8',
            type: 'fill_blank',
            sentence: 'Je to ___ ostré.',
            translation: 'It is too spicy.',
            options: ['príliš', 'málo', 'iba', 'asi'],
            correctIndex: 0,
          },
          {
            id: 'u3l5-9',
            type: 'multiple_choice',
            prompt: 'How do you say "Bon appétit / Enjoy"?',
            options: ['Dobrú chuť', 'Na zdravie', 'Ďakujem', 'Prosím'],
            correctIndex: 0,
          },
          {
            id: 'u3l5-10',
            type: 'translate_tiles',
            prompt: "Translate: I'm thirsty",
            answer: ['Som', 'smädný'],
            distractors: ['hladný', 'unavený'],
          },
          {
            id: 'u3l5-11',
            type: 'say_this',
            target: 'Dobrú chuť',
            meaning: 'Enjoy your meal',
            acceptedAnswers: ['Dobru chut', 'Dobrú chuť'],
          },
          {
            id: 'u3l5-12',
            type: 'say_this',
            target: 'Ešte jedno, prosím',
            meaning: 'One more, please',
            acceptedAnswers: ['Este jedno, prosim', 'Ešte jedno prosím'],
          },
        ],
      },
    ],
  },
  {
    id: 'unit-4',
    title: 'Family',
    description: 'Talk about family members.',
    color: '#a855f7',
    lessons: [
      {
        id: 'u4-l1',
        title: 'Parents',
        description: 'Mother & father',
        xp: 15,
        exercises: [
          {
            id: 'u4l1-1',
            type: 'multiple_choice',
            prompt: 'How do you say "mother"?',
            promptHint: 'mama / matka',
            options: ['mama', 'otec', 'brat', 'sestra'],
            correctIndex: 0,
          },
          {
            id: 'u4l1-2',
            type: 'word_match',
            prompt: 'father',
            options: ['otec', 'mama', 'syn', 'dcéra'],
            correctIndex: 0,
            promptHint: 'otec (OH-tets)',
          },
          {
            id: 'u4l1-3',
            type: 'fill_blank',
            sentence: 'Moja ___ sa volá Eva.',
            translation: 'My mother is called Eva.',
            options: ['mama', 'otec', 'brat', 'pes'],
            correctIndex: 0,
          },
          {
            id: 'u4l1-4',
            type: 'match_pairs',
            pairs: [
              { left: 'mama', right: 'mom / mother' },
              { left: 'otec', right: 'father' },
              { left: 'rodičia', right: 'parents' },
              { left: 'rodina', right: 'family' },
            ],
          },
          {
            id: 'u4l1-5',
            type: 'translate_tiles',
            prompt: 'Translate: my father',
            answer: ['môj', 'otec'],
            distractors: ['moja', 'mama', 'brat'],
          },
          {
            id: 'u4l1-6',
            type: 'multiple_choice',
            prompt: '"Rodina" means…',
            options: ['family', 'friend', 'house', 'child'],
            correctIndex: 0,
          },
          {
            id: 'u4l1-7',
            type: 'word_match',
            prompt: 'parents',
            options: ['rodičia', 'deti', 'priatelia', 'susedia'],
            correctIndex: 0,
          },
          {
            id: 'u4l1-8',
            type: 'fill_blank',
            sentence: 'Môj ___ pracuje.',
            translation: 'My father works.',
            options: ['otec', 'mama', 'sestra', 'dcéra'],
            correctIndex: 0,
          },
          {
            id: 'u4l1-9',
            type: 'multiple_choice',
            prompt: 'Which is feminine "my"?',
            options: ['moja', 'môj', 'moje', 'naši'],
            correctIndex: 0,
          },
          {
            id: 'u4l1-10',
            type: 'translate_tiles',
            prompt: 'Translate: my family',
            answer: ['moja', 'rodina'],
            distractors: ['môj', 'otec', 'brat'],
          },
          {
            id: 'u4l1-11',
            type: 'say_this',
            target: 'mama',
            meaning: 'mom / mother',
            acceptedAnswers: ['matka'],
          },
          {
            id: 'u4l1-12',
            type: 'say_this',
            target: 'otec',
            meaning: 'father',
          },
],
      },
      {
        id: 'u4-l2',
        title: 'Siblings & kids',
        description: 'Brother, sister, children',
        xp: 15,
        exercises: [
          {
            id: 'u4l2-1',
            type: 'multiple_choice',
            prompt: 'How do you say "brother"?',
            options: ['brat', 'sestra', 'syn', 'stryko'],
            correctIndex: 0,
          },
          {
            id: 'u4l2-2',
            type: 'word_match',
            prompt: 'sister',
            options: ['sestra', 'brat', 'dcéra', 'teta'],
            correctIndex: 0,
          },
          {
            id: 'u4l2-3',
            type: 'match_pairs',
            pairs: [
              { left: 'syn', right: 'son' },
              { left: 'dcéra', right: 'daughter' },
              { left: 'dieťa', right: 'child' },
              { left: 'deti', right: 'children' },
            ],
          },
          {
            id: 'u4l2-4',
            type: 'fill_blank',
            sentence: 'Mám jedného ___.',
            translation: 'I have one brother.',
            options: ['brata', 'sestru', 'mamu', 'otca'],
            correctIndex: 0,
          },
          {
            id: 'u4l2-5',
            type: 'translate_tiles',
            prompt: 'Translate: my sister',
            answer: ['moja', 'sestra'],
            distractors: ['môj', 'brat', 'syn'],
          },
          {
            id: 'u4l2-6',
            type: 'multiple_choice',
            prompt: '"Dieťa" means…',
            options: ['child', 'man', 'woman', 'baby animal'],
            correctIndex: 0,
          },
          {
            id: 'u4l2-7',
            type: 'word_match',
            prompt: 'son',
            options: ['syn', 'dcéra', 'brat', 'otec'],
            correctIndex: 0,
          },
          {
            id: 'u4l2-8',
            type: 'fill_blank',
            sentence: 'Ich ___ sa volá Lucia.',
            translation: 'Their daughter is called Lucia.',
            options: ['dcéra', 'syn', 'otec', 'brat'],
            correctIndex: 0,
          },
          {
            id: 'u4l2-9',
            type: 'multiple_choice',
            prompt: 'What does "deti" mean?',
            options: ['children', 'parents', 'friends', 'teachers'],
            correctIndex: 0,
          },
          {
            id: 'u4l2-10',
            type: 'match_pairs',
            pairs: [
              { left: 'brat', right: 'brother' },
              { left: 'sestra', right: 'sister' },
              { left: 'syn', right: 'son' },
              { left: 'dcéra', right: 'daughter' },
            ],
          },
          {
            id: 'u4l2-11',
            type: 'say_this',
            target: 'brat',
            meaning: 'brother',
          },
          {
            id: 'u4l2-12',
            type: 'say_this',
            target: 'sestra',
            meaning: 'sister',
          },
],
      },
      {
        id: 'u4-l3',
        title: 'Relatives',
        description: 'Grandparents & more',
        xp: 20,
        exercises: [
          {
            id: 'u4l3-1',
            type: 'multiple_choice',
            prompt: 'How do you say "grandmother"?',
            options: ['stará mama / babička', 'stará otec', 'teta', 'neter'],
            correctIndex: 0,
          },
          {
            id: 'u4l3-2',
            type: 'word_match',
            prompt: 'grandfather',
            options: ['starý otec / dedko', 'stará mama', 'stryko', 'synovec'],
            correctIndex: 0,
          },
          {
            id: 'u4l3-3',
            type: 'match_pairs',
            pairs: [
              { left: 'teta', right: 'aunt' },
              { left: 'stryko / ujo', right: 'uncle' },
              { left: 'bratranec', right: 'male cousin' },
              { left: 'sesternica', right: 'female cousin' },
            ],
          },
          {
            id: 'u4l3-4',
            type: 'fill_blank',
            sentence: 'Moja ___ pečie koláče.',
            translation: 'My grandmother bakes cakes.',
            options: ['babička', 'otec', 'brat', 'syn'],
            correctIndex: 0,
          },
          {
            id: 'u4l3-5',
            type: 'translate_tiles',
            prompt: 'Translate: my aunt',
            answer: ['moja', 'teta'],
            distractors: ['môj', 'ujo', 'brat'],
          },
          {
            id: 'u4l3-6',
            type: 'multiple_choice',
            prompt: '"Manžel" means…',
            options: ['husband', 'wife', 'friend', 'neighbor'],
            correctIndex: 0,
          },
          {
            id: 'u4l3-7',
            type: 'word_match',
            prompt: 'wife',
            options: ['manželka', 'manžel', 'priateľka', 'sestra'],
            correctIndex: 0,
          },
          {
            id: 'u4l3-8',
            type: 'fill_blank',
            sentence: 'To je môj ___.',
            translation: 'That is my uncle.',
            options: ['ujo', 'teta', 'mama', 'sestra'],
            correctIndex: 0,
          },
          {
            id: 'u4l3-9',
            type: 'multiple_choice',
            prompt: 'What does "priateľ" mean?',
            options: ['friend (m.) / boyfriend', 'enemy', 'teacher', 'boss'],
            correctIndex: 0,
          },
          {
            id: 'u4l3-10',
            type: 'match_pairs',
            pairs: [
              { left: 'babička', right: 'grandma' },
              { left: 'dedko', right: 'grandpa' },
              { left: 'manžel', right: 'husband' },
              { left: 'manželka', right: 'wife' },
            ],
          },
        ],
      },

      {
        id: 'u4-l4',
        title: 'My family',
        description: 'Talk about your family',
        xp: 20,
        exercises: [
          {
            id: 'u4l4-1',
            type: 'multiple_choice',
            prompt: 'How do you say "I have a brother"?',
            promptHint: 'Mám brata',
            options: ['Mám brata', 'Som brat', 'Idem brat', 'Chcem brat'],
            correctIndex: 0,
          },
          {
            id: 'u4l4-2',
            type: 'translate_tiles',
            prompt: 'Translate: This is my sister',
            answer: ['To', 'je', 'moja', 'sestra'],
            distractors: ['brat', 'otec'],
          },
          {
            id: 'u4l4-3',
            type: 'fill_blank',
            sentence: 'Moja ___ je učiteľka.',
            translation: 'My mom is a teacher.',
            options: ['mama', 'otec', 'brat', 'syn'],
            correctIndex: 0,
          },
          {
            id: 'u4l4-4',
            type: 'word_match',
            prompt: 'we / our family often "naša rodina"',
            options: ['my', 'vy', 'oni', 'ty'],
            correctIndex: 0,
            promptHint: 'my (MEE) — we',
          },
          {
            id: 'u4l4-5',
            type: 'match_pairs',
            pairs: [
              { left: 'Mám brata', right: 'I have a brother' },
              { left: 'Mám sestru', right: 'I have a sister' },
              { left: 'naša rodina', right: 'our family' },
              { left: 'jedináčik', right: 'only child' },
            ],
          },
          {
            id: 'u4l4-6',
            type: 'multiple_choice',
            prompt: 'What does "Som jedináčik" mean?',
            options: ["I'm an only child", "I'm married", "I'm a twin", "I'm the youngest"],
            correctIndex: 0,
          },
          {
            id: 'u4l4-7',
            type: 'fill_blank',
            sentence: 'Mám dvoch ___.',
            translation: 'I have two sons.',
            options: ['synov', 'dcéry', 'bratov', 'otcov'],
            correctIndex: 0,
          },
          {
            id: 'u4l4-8',
            type: 'word_match',
            prompt: 'parents',
            options: ['rodičia', 'deti', 'súrodenci', 'priateľ'],
            correctIndex: 0,
          },
          {
            id: 'u4l4-9',
            type: 'translate_tiles',
            prompt: 'Translate: our family',
            answer: ['naša', 'rodina'],
            distractors: ['moja', 'tvoja', 'brat'],
          },
          {
            id: 'u4l4-10',
            type: 'multiple_choice',
            prompt: 'How do you say "I love my family"?',
            options: ['Ľúbim svoju rodinu', 'Mám hlad', 'Som doma', 'Chcem vodu'],
            correctIndex: 0,
          },
          {
            id: 'u4l4-11',
            type: 'say_this',
            target: 'Mám brata',
            meaning: 'I have a brother',
            acceptedAnswers: ['Mam brata', 'Mám brata'],
          },
          {
            id: 'u4l4-12',
            type: 'say_this',
            target: 'To je moja sestra',
            meaning: 'This is my sister',
          },
        ],
      },
      {
        id: 'u4-l5',
        title: 'People around me',
        description: 'Friends, neighbors, colleagues',
        xp: 20,
        exercises: [
          {
            id: 'u4l5-1',
            type: 'multiple_choice',
            prompt: 'How do you say "neighbor"?',
            promptHint: 'sused / suseda',
            options: ['sused', 'priateľ', 'učiteľ', 'lekár'],
            correctIndex: 0,
          },
          {
            id: 'u4l5-2',
            type: 'word_match',
            prompt: 'teacher',
            options: ['učiteľ', 'žiak', 'lekár', 'kamarát'],
            correctIndex: 0,
          },
          {
            id: 'u4l5-3',
            type: 'match_pairs',
            pairs: [
              { left: 'kamarát', right: 'buddy / friend (casual)' },
              { left: 'kolega', right: 'colleague' },
              { left: 'sused', right: 'neighbor (m.)' },
              { left: 'žiak', right: 'pupil / student' },
            ],
          },
          {
            id: 'u4l5-4',
            type: 'fill_blank',
            sentence: 'To je môj ___.',
            translation: 'That is my friend (casual).',
            options: ['kamarát', 'stôl', 'dom', 'čaj'],
            correctIndex: 0,
          },
          {
            id: 'u4l5-5',
            type: 'translate_tiles',
            prompt: 'Translate: She is nice',
            answer: ['Ona', 'je', 'milá'],
            distractors: ['On', 'zlý', 'veľký'],
          },
          {
            id: 'u4l5-6',
            type: 'multiple_choice',
            prompt: '"Lekár" means…',
            options: ['doctor', 'lawyer', 'driver', 'cook'],
            correctIndex: 0,
          },
          {
            id: 'u4l5-7',
            type: 'word_match',
            prompt: 'child / kid (neutral "dieťa")',
            options: ['dieťa', 'dospelý', 'starý', 'mladý'],
            correctIndex: 0,
          },
          {
            id: 'u4l5-8',
            type: 'fill_blank',
            sentence: 'On je môj ___.',
            translation: 'He is my colleague.',
            options: ['kolega', 'mama', 'sestra', 'babička'],
            correctIndex: 0,
          },
          {
            id: 'u4l5-9',
            type: 'multiple_choice',
            prompt: 'How do you say "Who is that?"?',
            options: ['Kto je to?', 'Čo je to?', 'Kde je to?', 'Ako je to?'],
            correctIndex: 0,
          },
          {
            id: 'u4l5-10',
            type: 'match_pairs',
            pairs: [
              { left: 'Kto je to?', right: 'Who is that?' },
              { left: 'učiteľ', right: 'teacher' },
              { left: 'lekár', right: 'doctor' },
              { left: 'suseda', right: 'neighbor (f.)' },
            ],
          },
          {
            id: 'u4l5-11',
            type: 'say_this',
            target: 'Kto je to?',
            meaning: 'Who is that?',
          },
          {
            id: 'u4l5-12',
            type: 'say_this',
            target: 'To je môj kamarát',
            meaning: 'That is my friend',
            acceptedAnswers: ['To je moj kamarat', 'To je môj kamarát'],
          },
        ],
      },
    ],
  },
  {
    id: 'unit-5',
    title: 'Colors & Verbs',
    description: 'Describe things and use everyday verbs.',
    color: '#ef4444',
    lessons: [
      {
        id: 'u5-l1',
        title: 'Colors',
        description: 'Basic colors',
        xp: 15,
        exercises: [
          {
            id: 'u5l1-1',
            type: 'multiple_choice',
            prompt: 'How do you say "red"?',
            options: ['červený', 'modrý', 'zelený', 'žltý'],
            correctIndex: 0,
            promptHint: 'červený (CHEHR-veh-nee)',
          },
          {
            id: 'u5l1-2',
            type: 'word_match',
            prompt: 'blue',
            options: ['modrý', 'červený', 'biely', 'čierny'],
            correctIndex: 0,
          },
          {
            id: 'u5l1-3',
            type: 'match_pairs',
            pairs: [
              { left: 'zelený', right: 'green' },
              { left: 'žltý', right: 'yellow' },
              { left: 'biely', right: 'white' },
              { left: 'čierny', right: 'black' },
            ],
          },
          {
            id: 'u5l1-4',
            type: 'fill_blank',
            sentence: 'To je ___ auto.',
            translation: 'That is a red car. (neut. form often "červené")',
            options: ['červené', 'vysoké', 'staré', 'nové'],
            correctIndex: 0,
          },
          {
            id: 'u5l1-5',
            type: 'translate_tiles',
            prompt: 'Translate: green',
            answer: ['zelený'],
            distractors: ['modrý', 'červený', 'žltý'],
          },
          {
            id: 'u5l1-6',
            type: 'multiple_choice',
            prompt: '"Oranžový" means…',
            options: ['orange', 'purple', 'pink', 'brown'],
            correctIndex: 0,
          },
          {
            id: 'u5l1-7',
            type: 'word_match',
            prompt: 'white',
            options: ['biely', 'čierny', 'sivý', 'hnedý'],
            correctIndex: 0,
          },
          {
            id: 'u5l1-8',
            type: 'fill_blank',
            sentence: 'Obloha je ___.',
            translation: 'The sky is blue.',
            options: ['modrá', 'červená', 'zelená', 'žltá'],
            correctIndex: 0,
          },
          {
            id: 'u5l1-9',
            type: 'multiple_choice',
            prompt: 'What color is "hnedý"?',
            options: ['brown', 'gray', 'pink', 'gold'],
            correctIndex: 0,
          },
          {
            id: 'u5l1-10',
            type: 'match_pairs',
            pairs: [
              { left: 'červený', right: 'red' },
              { left: 'modrý', right: 'blue' },
              { left: 'zelený', right: 'green' },
              { left: 'oranžový', right: 'orange' },
            ],
          },
        ],
      },
      {
        id: 'u5-l2',
        title: 'Common verbs',
        description: 'to be, have, go, want…',
        xp: 20,
        exercises: [
          {
            id: 'u5l2-1',
            type: 'multiple_choice',
            prompt: 'How do you say "I am"?',
            options: ['Som', 'Mám', 'Idem', 'Chcem'],
            correctIndex: 0,
          },
          {
            id: 'u5l2-2',
            type: 'word_match',
            prompt: 'I have',
            options: ['Mám', 'Som', 'Idem', 'Vidím'],
            correctIndex: 0,
          },
          {
            id: 'u5l2-3',
            type: 'fill_blank',
            sentence: '___ domov.',
            translation: "I'm going home.",
            options: ['Idem', 'Som', 'Mám', 'Chcem'],
            correctIndex: 0,
          },
          {
            id: 'u5l2-4',
            type: 'match_pairs',
            pairs: [
              { left: 'byť', right: 'to be' },
              { left: 'mať', right: 'to have' },
              { left: 'ísť', right: 'to go' },
              { left: 'chcieť', right: 'to want' },
            ],
          },
          {
            id: 'u5l2-5',
            type: 'translate_tiles',
            prompt: 'Translate: I want to go',
            answer: ['Chcem', 'ísť'],
            distractors: ['Som', 'Mám', 'domov'],
          },
          {
            id: 'u5l2-6',
            type: 'multiple_choice',
            prompt: '"Rozumiem" means…',
            options: ['I understand', 'I speak', 'I write', 'I read'],
            correctIndex: 0,
          },
          {
            id: 'u5l2-7',
            type: 'word_match',
            prompt: 'I speak',
            options: ['Hovorím', 'Čítam', 'Píšem', 'Počúvam'],
            correctIndex: 0,
          },
          {
            id: 'u5l2-8',
            type: 'fill_blank',
            sentence: '___ po slovensky.',
            translation: 'I speak Slovak.',
            options: ['Hovorím', 'Idem', 'Som', 'Mám'],
            correctIndex: 0,
          },
          {
            id: 'u5l2-9',
            type: 'translate_tiles',
            prompt: 'Translate: I understand',
            answer: ['Rozumiem'],
            distractors: ['Hovorím', 'Neviem', 'Áno'],
          },
          {
            id: 'u5l2-10',
            type: 'multiple_choice',
            prompt: 'How do you say "I don\'t know"?',
            options: ['Neviem', 'Nie', 'Nemám', 'Nerozumiem'],
            correctIndex: 0,
          },
          {
            id: 'u5l2-11',
            type: 'match_pairs',
            pairs: [
              { left: 'Som', right: 'I am' },
              { left: 'Mám', right: 'I have' },
              { left: 'Idem', right: 'I go / I\'m going' },
              { left: 'Chcem', right: 'I want' },
            ],
          },
          {
            id: 'u5l2-12',
            type: 'word_match',
            prompt: "I don't understand",
            options: ['Nerozumiem', 'Neviem', 'Nemám', 'Nechcem'],
            correctIndex: 0,
          },
        ],
      },
      {
        id: 'u5-l3',
        title: 'Describe it',
        description: 'Big, small, good…',
        xp: 20,
        exercises: [
          {
            id: 'u5l3-1',
            type: 'multiple_choice',
            prompt: 'How do you say "big"?',
            options: ['veľký', 'malý', 'dlhý', 'krátky'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-2',
            type: 'word_match',
            prompt: 'small',
            options: ['malý', 'veľký', 'nový', 'starý'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-3',
            type: 'match_pairs',
            pairs: [
              { left: 'dobrý', right: 'good' },
              { left: 'zlý', right: 'bad' },
              { left: 'nový', right: 'new' },
              { left: 'starý', right: 'old' },
            ],
          },
          {
            id: 'u5l3-4',
            type: 'fill_blank',
            sentence: 'To je ___ dom.',
            translation: 'That is a big house.',
            options: ['veľký', 'malý', 'zlý', 'krátky'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-5',
            type: 'translate_tiles',
            prompt: 'Translate: a good day',
            answer: ['dobrý', 'deň'],
            distractors: ['zlý', 'večer', 'malý'],
          },
          {
            id: 'u5l3-6',
            type: 'multiple_choice',
            prompt: '"Krásny" means…',
            options: ['beautiful / nice', 'ugly', 'cheap', 'expensive'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-7',
            type: 'word_match',
            prompt: 'hot (temperature / spicy sense often "pikantný")',
            options: ['horúci', 'studený', 'teplý', 'vlhký'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-8',
            type: 'fill_blank',
            sentence: 'Káva je ___.',
            translation: 'The coffee is hot.',
            options: ['horúca', 'studená', 'malá', 'nová'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-9',
            type: 'multiple_choice',
            prompt: 'What does "ľahký" mean?',
            options: ['easy / light', 'hard / heavy', 'fast', 'slow'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-10',
            type: 'match_pairs',
            pairs: [
              { left: 'veľký', right: 'big' },
              { left: 'malý', right: 'small' },
              { left: 'krásny', right: 'beautiful' },
              { left: 'ľahký', right: 'easy / light' },
            ],
          },
          {
            id: 'u5l3-11',
            type: 'say_this',
            target: 'Je to krásne',
            meaning: 'It is beautiful',
            acceptedAnswers: ['Je to krasne'],
          },
          {
            id: 'u5l3-12',
            type: 'multiple_choice',
            prompt: 'What does "starý" mean?',
            options: ['old', 'new', 'young', 'tall'],
            correctIndex: 0,
          },
          {
            id: 'u5l3-13',
            type: 'word_match',
            prompt: 'cold',
            options: ['studený', 'horúci', 'sladký', 'rýchly'],
            correctIndex: 0,
            promptHint: 'studený',
          },
          {
            id: 'u5l3-14',
            type: 'match_pairs',
            pairs: [
              { left: 'nový', right: 'new' },
              { left: 'starý', right: 'old' },
              { left: 'studený', right: 'cold' },
              { left: 'dobrý', right: 'good' },
            ],
          },
        ],
      },

      {
        id: 'u5-l4',
        title: 'More verbs',
        description: 'Eat, drink, see, hear…',
        xp: 20,
        exercises: [
          {
            id: 'u5l4-1',
            type: 'multiple_choice',
            prompt: 'How do you say "I eat"?',
            promptHint: 'Jem',
            options: ['Jem', 'Pijem', 'Vidím', 'Počujem'],
            correctIndex: 0,
          },
          {
            id: 'u5l4-2',
            type: 'word_match',
            prompt: 'I drink',
            options: ['Pijem', 'Jem', 'Spím', 'Čítam'],
            correctIndex: 0,
          },
          {
            id: 'u5l4-3',
            type: 'match_pairs',
            pairs: [
              { left: 'jesť', right: 'to eat' },
              { left: 'piť', right: 'to drink' },
              { left: 'vidieť', right: 'to see' },
              { left: 'počuť', right: 'to hear' },
            ],
          },
          {
            id: 'u5l4-4',
            type: 'fill_blank',
            sentence: '___ knihu.',
            translation: "I'm reading a book.",
            options: ['Čítam', 'Píšem', 'Pijem', 'Spím'],
            correctIndex: 0,
          },
          {
            id: 'u5l4-5',
            type: 'translate_tiles',
            prompt: 'Translate: I see',
            answer: ['Vidím'],
            distractors: ['Počujem', 'Jem', 'Idem'],
          },
          {
            id: 'u5l4-6',
            type: 'multiple_choice',
            prompt: '"Spím" means…',
            options: ['I sleep / I\'m sleeping', 'I speak', 'I stand', 'I sit'],
            correctIndex: 0,
          },
          {
            id: 'u5l4-7',
            type: 'word_match',
            prompt: 'I write',
            options: ['Píšem', 'Čítam', 'Počúvam', 'Hovorím'],
            correctIndex: 0,
          },
          {
            id: 'u5l4-8',
            type: 'fill_blank',
            sentence: '___ vodu.',
            translation: "I'm drinking water.",
            options: ['Pijem', 'Jem', 'Mám', 'Som'],
            correctIndex: 0,
          },
          {
            id: 'u5l4-9',
            type: 'multiple_choice',
            prompt: 'How do you say "I hear"?',
            options: ['Počujem', 'Vidím', 'Cítim', 'Myslím'],
            correctIndex: 0,
          },
          {
            id: 'u5l4-10',
            type: 'match_pairs',
            pairs: [
              { left: 'Jem', right: 'I eat' },
              { left: 'Pijem', right: 'I drink' },
              { left: 'Čítam', right: 'I read' },
              { left: 'Píšem', right: 'I write' },
            ],
          },
          {
            id: 'u5l4-11',
            type: 'say_this',
            target: 'Pijem vodu',
            meaning: "I'm drinking water",
          },
          {
            id: 'u5l4-12',
            type: 'say_this',
            target: 'Čítam knihu',
            meaning: "I'm reading a book",
            acceptedAnswers: ['Citam knihu', 'Čítam knihu'],
          },
        ],
      },
      {
        id: 'u5-l5',
        title: 'Ask & describe',
        description: 'Questions and adjectives',
        xp: 20,
        exercises: [
          {
            id: 'u5l5-1',
            type: 'multiple_choice',
            prompt: 'How do you say "What is that?"?',
            options: ['Čo je to?', 'Kto je to?', 'Kde je to?', 'Ako je to?'],
            correctIndex: 0,
            promptHint: 'Čo je to?',
          },
          {
            id: 'u5l5-2',
            type: 'word_match',
            prompt: 'Where is…?',
            options: ['Kde je…?', 'Čo je…?', 'Kto je…?', 'Prečo je…?'],
            correctIndex: 0,
          },
          {
            id: 'u5l5-3',
            type: 'match_pairs',
            pairs: [
              { left: 'rýchly', right: 'fast' },
              { left: 'pomalý', right: 'slow' },
              { left: 'ťažký', right: 'hard / heavy' },
              { left: 'ľahký', right: 'easy / light' },
            ],
          },
          {
            id: 'u5l5-4',
            type: 'fill_blank',
            sentence: 'Toto je ___ auto.',
            translation: 'This is a fast car.',
            options: ['rýchle', 'pomalé', 'studené', 'sladké'],
            correctIndex: 0,
          },
          {
            id: 'u5l5-5',
            type: 'translate_tiles',
            prompt: 'Translate: What is that?',
            answer: ['Čo', 'je', 'to'],
            distractors: ['Kde', 'Kto', 'Ako'],
          },
          {
            id: 'u5l5-6',
            type: 'multiple_choice',
            prompt: '"Prečo?" means…',
            options: ['Why?', 'When?', 'How?', 'Who?'],
            correctIndex: 0,
          },
          {
            id: 'u5l5-7',
            type: 'word_match',
            prompt: 'when',
            options: ['kedy', 'kde', 'ako', 'prečo'],
            correctIndex: 0,
          },
          {
            id: 'u5l5-8',
            type: 'fill_blank',
            sentence: 'Je to ___ ťažké.',
            translation: 'It is very hard.',
            options: ['veľmi', 'málo', 'iba', 'asi'],
            correctIndex: 0,
          },
          {
            id: 'u5l5-9',
            type: 'multiple_choice',
            prompt: 'How do you say "Please speak slowly"?',
            options: ['Hovorte pomaly, prosím', 'Hovorte rýchlo', 'Nehovorte', 'Počúvajte'],
            correctIndex: 0,
          },
          {
            id: 'u5l5-10',
            type: 'match_pairs',
            pairs: [
              { left: 'Čo?', right: 'What?' },
              { left: 'Kde?', right: 'Where?' },
              { left: 'Kedy?', right: 'When?' },
              { left: 'Prečo?', right: 'Why?' },
            ],
          },
          {
            id: 'u5l5-11',
            type: 'say_this',
            target: 'Čo je to?',
            meaning: 'What is that?',
            acceptedAnswers: ['Co je to', 'Čo je to'],
          },
          {
            id: 'u5l5-12',
            type: 'say_this',
            target: 'Hovorte pomaly, prosím',
            meaning: 'Please speak slowly',
            acceptedAnswers: ['Hovorte pomaly prosim', 'Hovorte pomaly, prosím'],
          },
        ],
      },
    ],
  },
]

export function getLessonById(lessonId: string) {
  for (const unit of curriculum) {
    const lesson = unit.lessons.find((l) => l.id === lessonId)
    if (lesson) return { unit, lesson }
  }
  return null
}

export function getAllLessonIds(): string[] {
  return curriculum.flatMap((u) => u.lessons.map((l) => l.id))
}

