/** Extra Slovak↔English pairs for practice games (additive; does not change lesson IDs). */
export interface VocabPair {
  sk: string
  en: string
}

export const GAMES_VOCAB_BANK: VocabPair[] = [
  // Unit 1 — greetings & basics
  { sk: 'Ahoj', en: 'Hello / Hi' },
  { sk: 'Čau', en: 'Bye / Hi (casual)' },
  { sk: 'Ďakujem', en: 'Thank you' },
  { sk: 'Ďakujem pekne', en: 'Thank you very much' },
  { sk: 'Prosím', en: "Please / You're welcome" },
  { sk: 'Áno', en: 'Yes' },
  { sk: 'Nie', en: 'No' },
  { sk: 'Dovidenia', en: 'Goodbye' },
  { sk: 'Dobré ráno', en: 'Good morning' },
  { sk: 'Dobrý deň', en: 'Good day' },
  { sk: 'Dobrý večer', en: 'Good evening' },
  { sk: 'Dobrú noc', en: 'Good night' },
  { sk: 'Prepáčte', en: 'Excuse me / Sorry (formal)' },
  { sk: 'Prepáč', en: 'Sorry (informal)' },
  { sk: 'Ako sa máš?', en: 'How are you? (informal)' },
  { sk: 'Ako sa máte?', en: 'How are you? (formal)' },
  { sk: 'Mám sa dobre', en: "I'm fine" },
  { sk: 'Ako sa voláš?', en: 'What is your name?' },
  { sk: 'Volám sa…', en: 'My name is…' },
  { sk: 'Teší ma', en: 'Nice to meet you' },
  { sk: 'Som zo Slovenska', en: "I'm from Slovakia" },
  { sk: 'Odkiaľ si?', en: 'Where are you from?' },
  { sk: 'Hovorím po slovensky', en: 'I speak Slovak' },
  { sk: 'Bývam tu', en: 'I live here' },
  { sk: 'Vitaj', en: 'Welcome (informal)' },
  { sk: 'Vitajte', en: 'Welcome (formal)' },
  { sk: 'Veľa šťastia', en: 'Good luck' },
  { sk: 'Všetko najlepšie', en: 'All the best' },
  { sk: 'Na zdravie', en: 'Cheers / Bless you' },
  { sk: 'Do zajtra', en: 'See you tomorrow' },
  { sk: 'trochu', en: 'a little / a bit' },

  // Unit 2 — numbers
  { sk: 'nula', en: 'zero' },
  { sk: 'jeden', en: 'one' },
  { sk: 'dva', en: 'two' },
  { sk: 'tri', en: 'three' },
  { sk: 'štyri', en: 'four' },
  { sk: 'päť', en: 'five' },
  { sk: 'šesť', en: 'six' },
  { sk: 'sedem', en: 'seven' },
  { sk: 'osem', en: 'eight' },
  { sk: 'deväť', en: 'nine' },
  { sk: 'desať', en: 'ten' },
  { sk: 'jedenásť', en: 'eleven' },
  { sk: 'dvanásť', en: 'twelve' },
  { sk: 'pätnásť', en: 'fifteen' },
  { sk: 'dvadsať', en: 'twenty' },
  { sk: 'tridsať', en: 'thirty' },
  { sk: 'štyridsať', en: 'forty' },
  { sk: 'päťdesiat', en: 'fifty' },
  { sk: 'šesťdesiat', en: 'sixty' },
  { sk: 'sedemdesiat', en: 'seventy' },
  { sk: 'osemdesiat', en: 'eighty' },
  { sk: 'deväťdesiat', en: 'ninety' },
  { sk: 'sto', en: 'one hundred' },
  { sk: 'Koľko?', en: 'How many? / How much?' },
  { sk: 'Koľko to stojí?', en: 'How much does it cost?' },
  { sk: 'Koľko máš rokov?', en: 'How old are you?' },
  { sk: 'Mám dvadsať rokov', en: "I'm twenty years old" },
  { sk: 'veľa', en: 'a lot / many' },
  { sk: 'málo', en: 'a little / few' },
  { sk: 'nič', en: 'nothing' },
  { sk: 'iba', en: 'only' },
  { sk: 'asi', en: 'about / approximately' },
  { sk: 'pol', en: 'half' },

  // Unit 3 — food & drink
  { sk: 'voda', en: 'water' },
  { sk: 'káva', en: 'coffee' },
  { sk: 'čaj', en: 'tea' },
  { sk: 'pivo', en: 'beer' },
  { sk: 'víno', en: 'wine' },
  { sk: 'mlieko', en: 'milk' },
  { sk: 'džús', en: 'juice' },
  { sk: 'chlieb', en: 'bread' },
  { sk: 'syr', en: 'cheese' },
  { sk: 'mäso', en: 'meat' },
  { sk: 'ryba', en: 'fish' },
  { sk: 'polievka', en: 'soup' },
  { sk: 'šalát', en: 'salad' },
  { sk: 'ryža', en: 'rice' },
  { sk: 'zemiaky', en: 'potatoes' },
  { sk: 'vajce', en: 'egg' },
  { sk: 'cukor', en: 'sugar' },
  { sk: 'jablko', en: 'apple' },
  { sk: 'banán', en: 'banana' },
  { sk: 'pomaranč', en: 'orange (fruit)' },
  { sk: 'jahoda', en: 'strawberry' },
  { sk: 'hrozno', en: 'grapes' },
  { sk: 'hruška', en: 'pear' },
  { sk: 'ovocie', en: 'fruit' },
  { sk: 'zmrzlina', en: 'ice cream' },
  { sk: 'čokoláda', en: 'chocolate' },
  { sk: 'Chcem', en: 'I want' },
  { sk: 'Mám rád', en: 'I like (m.)' },
  { sk: 'chutné', en: 'delicious / tasty' },
  { sk: 'účet', en: 'the bill' },
  { sk: 'jedálny lístok', en: 'menu' },
  { sk: 'Som hladný', en: "I'm hungry (m.)" },
  { sk: 'Som smädný', en: "I'm thirsty (m.)" },
  { sk: 'Dobrú chuť', en: 'Enjoy your meal' },
  { sk: 'Ešte jedno, prosím', en: 'One more, please' },
  { sk: 'soľ', en: 'salt' },
  { sk: 'nôž', en: 'knife' },
  { sk: 'vidlička', en: 'fork' },
  { sk: 'lyžica', en: 'spoon' },
  { sk: 'tanier', en: 'plate' },
  { sk: 'pohár', en: 'glass / cup' },

  // Unit 4 — family & people
  { sk: 'mama', en: 'mom / mother' },
  { sk: 'otec', en: 'father' },
  { sk: 'brat', en: 'brother' },
  { sk: 'sestra', en: 'sister' },
  { sk: 'syn', en: 'son' },
  { sk: 'dcéra', en: 'daughter' },
  { sk: 'rodina', en: 'family' },
  { sk: 'rodičia', en: 'parents' },
  { sk: 'deti', en: 'children' },
  { sk: 'dieťa', en: 'child' },
  { sk: 'priateľ', en: 'friend / boyfriend' },
  { sk: 'priateľka', en: 'friend / girlfriend' },
  { sk: 'kamarát', en: 'buddy / friend' },
  { sk: 'manžel', en: 'husband' },
  { sk: 'manželka', en: 'wife' },
  { sk: 'babička', en: 'grandma' },
  { sk: 'dedko', en: 'grandpa' },
  { sk: 'ujo', en: 'uncle' },
  { sk: 'teta', en: 'aunt' },
  { sk: 'sused', en: 'neighbor (m.)' },
  { sk: 'kolega', en: 'colleague' },
  { sk: 'učiteľ', en: 'teacher' },
  { sk: 'lekár', en: 'doctor' },
  { sk: 'Mám brata', en: 'I have a brother' },
  { sk: 'Mám sestru', en: 'I have a sister' },
  { sk: 'naša rodina', en: 'our family' },
  { sk: 'Kto je to?', en: 'Who is that?' },

  // Unit 5 — colors, verbs, adjectives
  { sk: 'červený', en: 'red' },
  { sk: 'modrý', en: 'blue' },
  { sk: 'zelený', en: 'green' },
  { sk: 'žltý', en: 'yellow' },
  { sk: 'biely', en: 'white' },
  { sk: 'čierny', en: 'black' },
  { sk: 'oranžový', en: 'orange (color)' },
  { sk: 'hnedý', en: 'brown' },
  { sk: 'Som', en: 'I am' },
  { sk: 'Mám', en: 'I have' },
  { sk: 'Idem', en: "I go / I'm going" },
  { sk: 'Rozumiem', en: 'I understand' },
  { sk: 'Nerozumiem', en: "I don't understand" },
  { sk: 'Neviem', en: "I don't know" },
  { sk: 'Hovorím', en: 'I speak' },
  { sk: 'Jem', en: 'I eat' },
  { sk: 'Pijem', en: 'I drink' },
  { sk: 'Vidím', en: 'I see' },
  { sk: 'Počujem', en: 'I hear' },
  { sk: 'Čítam', en: 'I read' },
  { sk: 'Píšem', en: 'I write' },
  { sk: 'Spím', en: 'I sleep' },
  { sk: 'veľký', en: 'big' },
  { sk: 'malý', en: 'small' },
  { sk: 'krásny', en: 'beautiful' },
  { sk: 'horúci', en: 'hot' },
  { sk: 'studený', en: 'cold' },
  { sk: 'dobrý', en: 'good' },
  { sk: 'zlý', en: 'bad' },
  { sk: 'nový', en: 'new' },
  { sk: 'starý', en: 'old' },
  { sk: 'ľahký', en: 'easy / light' },
  { sk: 'ťažký', en: 'hard / heavy' },
  { sk: 'rýchly', en: 'fast' },
  { sk: 'pomalý', en: 'slow' },
  { sk: 'Dobre', en: 'Fine / OK / Well' },
  { sk: 'Výborne', en: 'Excellent' },
  { sk: 'Pomaly', en: 'Slowly' },
  { sk: 'Čo je to?', en: 'What is that?' },
  { sk: 'Kde je…?', en: 'Where is…?' },
  { sk: 'Kedy?', en: 'When?' },
  { sk: 'Prečo?', en: 'Why?' },
  { sk: 'Hovorte pomaly, prosím', en: 'Please speak slowly' },
  { sk: 'Pijem vodu', en: "I'm drinking water" },
  { sk: 'Čítam knihu', en: "I'm reading a book" },
  { sk: 'Je to krásne', en: 'It is beautiful' },
]
